
name: CI & CD

on:
  push:
    branches: [ mubashir ]
jobs:
  CI-AND-CD:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: cd hosting
        run: cd hosting
      - name: dir
        run: dir
      - name: cd hosting2
        working-directory: ./hosting
        run: dir
#       - name: deleting old build
#         run: rmdir www
      - name: Remove File
        uses: JesseTG/rm@v1.0.2
        with:
          path: /hosting/www
      - name: delete
        working-directory: ./hosting
        run: git rm -r www
      - name: cd hosting2
        working-directory: ./hosting
        run: dir
      - name: cd out
        run: cd ..
      - name: dir
        run: dir
      - name: Setup npm package
        run: npm install
      - name: Build Using npm
        run: |
          dir
          npm run build
        
#       - name: Deploy to Firebase
#         uses: w9jds/firebase-action@master
#         with:
#            args: deploy --only hosting
#         env:
#            FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
#            PROJECT_PATH: "./hosting"
