
name: CI & CD

on:
  push:
    branches: [ mubashir ]
jobs:
  CI-AND-CD:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: cd hosting
        run: cd hosting
      - name: dir
        run: dir
      - name: deleting old build
        run: rmdir www
      - name: cd out
        run: cd ..
      - name: Setup npm package
        run: npm install
      - name: Build Using npm
        run: node_modules/.bin/ionic build
        
#       - name: Deploy to Firebase
#         uses: w9jds/firebase-action@master
#         with:
#            args: deploy --only hosting
#         env:
#            FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
#            PROJECT_PATH: "./hosting"
